### ISSUE TITLE
can't open the .erp file

### ISSUE THREAD

**Issue by Guriado** [Ryder25/Ego-Engine-Modding#1]
i just downloaded one mod for f1 2016, but when i try to open the files .erp, my computer doesn't open them as .erp but open them as a folder, so when i am using your software, i can't select the .erp files so the software let me go into the folder and i can see the textures that are in it. can you help me?

the mod that i am using is **http://www.racedepartment.com/threads/williams-martini-racing-complete-team-package.127182/**

**Comment by Ryder25** [comment]
That's because the files from the mod are not erp files. They are, in fact, folders.

If you look at the mod readme, it tells you the location of the files that you need to open with the Archiver. From there you will need to import those dds files.
