### ISSUE TITLE
Unable to open file extracted from .erp file

### ISSUE THREAD

**Issue by Ho3n3r** [Ryder25/Ego-Engine-Modding#10]
I know F1 2017 is not supported by your products, but just in case you intend to update it, maybe this will help. Here is a full account of what I tried to do, to be as clear as possible, because F1 2017 file structures seem somewhat different from before.

I am trying to disable weather for career mode. The one way I have seen to do it, is to make all rain likelihood 0% for every track - found here: http://www.racedepartment.com/threads/can-i-disable-rain-for-all-tracks-in-f1-2016.137543/

However, first stumbling block for that, is that there are no tod.xml's any more, as required by the steps.

Next step was to open and explore <trackname>.erp, as I did below, and this is how the <trackname>_timeofday.layer (implied by the old tod files) look:
![image](https://user-images.githubusercontent.com/32883446/31687854-bdaaa39a-b38a-11e7-9708-3b71aa3b818e.png)

Then, after extracting the track's entire erp file, I get the 2 files mentioned above:
![image](https://user-images.githubusercontent.com/32883446/31687876-cc32a7d2-b38a-11e7-965f-28f6f5a32a45.png)

However, I don't know how to open them. Any advice?

I will add that I've tried to convert these files with the Ego File Converter, but clearly it's not possible, probably due to not being a valid format for that. Example of error when trying to convert:
![image](https://user-images.githubusercontent.com/32883446/31687901-dbf138be-b38a-11e7-9a90-2a8639c83bb8.png)

Opening it with Notepad++ just leads to a lot of gibberish.

So, the above is where I'm stuck. If anyone has any other ideas for the next step, it would be appreciated a lot.

**Comment by Ryder25** [comment]
Thanks for the detailed info. I'll have a look when I get a chance.

Can you send/upload the suzuka erp? I don't own the F1 2017 game so I don't have access to the files.

**Comment by Ho3n3r** [comment]
Thanks for the quick response!

I have a 50KB/s upload speed, and the .erp file is almost 500MB. I have uploaded the 2 files in the folder above though - .trackinfobin and .trackinfotex, if that helps for now. I will be uploading the .erp overnight, and will send you the link in about a day when I can access it again.

See link for 2 relevant files: https://drive.google.com/drive/folders/0B3vRrYRkqyC3RVdlR0hfdnZ2TDQ?usp=sharing

**Comment by Ho3n3r** [comment]
@Ryder25 here is the spa_francorchamps.erp, as requested: https://drive.google.com/file/d/0B3vRrYRkqyC3Mnk4dGlmYjBUS3M/view?usp=sharing

**Comment by BenutzerUser** [comment]
The two mentioned files are resources exports (no pkg, texture or xml). Afaik they can be edited with hex editor for the time being. (Though I have not yet edited and reimported one of those).
As resources exports did already exist in the previous games, I too once wondered if I missed a converter for those types.

**Comment by Ryder25** [comment]
One of those files (trackinfotex) I believe is simply a TGA file that you can open with an image editor. The other one I'm not sure.

The other files related to TOD in that ERP don't seem to resemble any of the data that used to be stored in the tod.xml from F1 2014 and older games. Not sure if that data is stored elsewhere, or if the TOD system is just works differently now.

**Comment by Ho3n3r** [comment]
@Ryder25 OK, thank you. I assume you can close this log then, as it's not a bug but an incorrect assumption on my end.

I will ask further questions on the Discord chat though, so that someone can maybe help me find a way to disable weather in career. No need for me to ask that over here.

Your awesome assistance is appreciated, and I will leave you a donation for your awesome tools when I get my salary.
