### ISSUE TITLE
Cant edit extracted DDS files in Photoshop CC 2018

### ISSUE THREAD

**Issue by danielw2081** [Ryder25/Ego-Engine-Modding#11]
(Im doing this with F1 2017 and the latest version of ERP Archiver) When exporting DDS files, I cant open them in Photoshop CC 2018, I get the message "Could not complete your request because of a program error. But I can open downloaded DDS files just fine. Any ideas as to why? This is what the icons look like, the one with the PS logo is the one i extracted that wont work with PS, and the one with the thumbnail of the image is the downloaded one that does work. SO I think theyre differently formatted somehow but I have no idea how.

Image: https://ibb.co/bLNjNb

And how the file details differ: https://ibb.co/gF3G2b

The one with no dimensions is the one I extracted.

**Comment by Ryder25** [comment]
The extracted texture might be a DDS file with a "DX10" format.  You need to make sure that your Photoshop supports these DX10 formats.  There are many different kinds, but the most popular are BC1, BC3, and BC7.

There's this plugin for Photoshop that supports opening these textures:
https://software.intel.com/en-us/articles/intel-texture-works-plugin

**Comment by danielw2081** [comment]
Yep thats what it was, appreciate it man :) Love your programs
