### ISSUE TITLE
Export of texture files are just black in photoshop

### ISSUE THREAD

**Issue by ronage** [Ryder25/Ego-Engine-Modding#12]
When I try to export any texture a dds file is created, but when I open it in Photoshop it's just a black screen.

**Comment by Ryder25** [comment]
You may not have a DDS plugin that supports that texture format.

Try the solution from this issue:
https://github.com/Ryder25/Ego-Engine-Modding/issues/11

**Comment by ronage** [comment]
Thanks for the fast reply. This worked with the 32bit version even if i have windows 10 64bit. Sorry I just should have read all the closed issues before posting.

**Comment by Ryder25** [comment]
No problem
