### ISSUE TITLE
F1 2010 dont work

### ISSUE THREAD

**Issue by wandamemp** [Ryder25/Ego-Engine-Modding#16]
i tried to open f1 2010 fils but everyteam is same at every track

**Comment by wandamemp** [comment]
it is for ctf editor

**Comment by Ryder25** [comment]
It has been a while since I looked at F1 2010 files, but if I remember correctly there are more ctf files than the one in the main car folder.  Try looking at the files inside of the "balanced" and "track" folders inside the car folder.

**Comment by wandamemp** [comment]
I tried open everything but all the cars have same traits at every single track.

**Comment by wandamemp** [comment]
Do I need to download the f1 2010 schema?or is it already included?

**Comment by Ryder25** [comment]
I just tried opening the files, and I saw plenty of differences between each car, and each track.  The schema is already included. Just open the ctf files in the "Formula 1" tab and it should work fine.

**Comment by wandamemp** [comment]
Is the files located at cars\fe2 for example?

**Comment by wandamemp** [comment]
Because I tried opening Red Bull and Ferrari in a particular race track,Yeongnam.Its all the same

**Comment by wandamemp** [comment]
I got it already.But i have another problem,it says access to path is denied.What can i do?

**Comment by Ryder25** [comment]
When does that error happen? Opening, saving? What folder/file are you working on?

**Comment by wandamemp** [comment]
Thanks for helping,I have solved the issue
