### ISSUE TITLE
Can't open exported textures

### ISSUE THREAD

**Issue by Xurda** [Ryder25/Ego-Engine-Modding#17]
I'm using the latest version of the ERP Archiver and I'm not able to open the exported textures with any program (gimp, paint.net, photoshop...), and I've already installed all the DDS plug-ins.
![49c9e8b251bb398fe55a8b1521f9ecae](https://user-images.githubusercontent.com/38036570/38244311-8b32b522-373a-11e8-8c47-de0db55748d3.png)

**Comment by Ryder25** [comment]
Try the solution from issue #11
