### ISSUE TITLE
Ego CTF Editor

### ISSUE THREAD

**Issue by Karambit74** [Ryder25/Ego-Engine-Modding#18]
Hi, I tried to edit F1 2017. There is no information where I should get the CTF or CVS files on F1 2017. Could you please be more specific where I should find to CTF or CVS in the game?

thanks

**Comment by Ryder25** [comment]
The way to modify car stats for F1 2017 is different.  You need the "ERP Archiver" for that.

An example is the ferrari team. The car file is an xml file named "ferrari.vtf" inside of "asset_groups/f1_2017_vehicle_package/teams/ferrari/wep/ferrari.erp".

I have never modified this game, so I'm not sure if this will actually work. You should confirm with someone who has done this before.  Maybe try asking in the [discord chat room](https://discord.gg/5bCjMqS).

**Comment by Karambit74** [comment]
Thank you for replying I really appreciate it. I will play around with ERP archiver.
