### ISSUE TITLE
EGO ERP Archiver (newest version 04/2018) not saving mipmaps

### ISSUE THREAD

**Issue by PR3D4TOR91** [Ryder25/Ego-Engine-Modding#19]
Everytime i want to import a .dds texture in F1 2017 it does not save the mipmap. It only saves them ONCE with new unedited files. Once i import a modded texture the mipmap replacement window does not pop up and it is just a 0kb file. 

Did never happen before. Running as admin does not help it. 

Any ideas?

**Comment by Ryder25** [comment]
Can you give me a step by step on how to reproduce this problem on my end? You can use a concrete example of which erp and texture you tried this with.

**Comment by PR3D4TOR91** [comment]
I do not know if it is reproducable. Yes, 6.1 

I import a helmet texture file 
use this for example: https://www.racedepartment.com/downloads/red-bull-helmet.19826/

I open up the incardriver 2017 .erp, go to search for "06" (com_06 helmet), then i choose the "xxx.d.tga" file, import textures, choose the right .dds file from the downloaded helmet, import it and usually it says i have to overwrite the .mipmaps. But it only does it ONE time per helmet texture (com 01-06 helmets) and then it just does not ask me if i wanna overwrite the .mipmaps file from the helmets anymore. It has worked absolutely flawless up until a few days ago. I have no clue what has happened.

**Comment by Ryder25** [comment]
I followed the steps you told me, by replacing the com_06 texture with the redbull.dds file from racedepartment.  I was able to save the mipmaps file.  I then tried overwriting the same texture (com_06) again with redbull.dds, and it still seemed to work fine. I guess I don't understand what you mean with the next step:

> But it only does it ONE time per helmet texture (com 01-06 helmets) and then it just does not ask me if i wanna overwrite the .mipmaps file from the helmets anymore.

Can you elaborate?

**Comment by PR3D4TOR91** [comment]
I have no clue what the issue is at all. 

There are several helmet texture files (com_0x-06 or even more then 06, i dont know)
I can replace every texture one time (01, 02, 03, ...) and it saves the mipmap. After that it just does not let me save the .mipmap file. The program shows that it is replaced in the preview but the mipmaps file is 0kb/not replaced.

Maybe i just reinstall the game.

**Comment by Ryder25** [comment]
Sorry, I don't know what else to try. I can't get the same problem on my computer.
