### ISSUE TITLE
EEA crashes on import on Windows 7

### ISSUE THREAD

**Issue by yuvalhq** [Ryder25/Ego-Engine-Modding#2]
hello.
I downloaded your program to modify my f1 2016 game.
when I try to change a texture by importing a new one the program freezes and crash.
it happened to me with 3 different mods..
thanks for the help!

**Comment by Ryder25** [comment]
Hey,

Is this happening on Windows 7 by any chance?  Can you explain the process you took before getting the error?

**Comment by yuvalhq** [comment]
hey thanks for answering!
yes I'm using win7...
when I want to change a texture in the game, i open up the EEA.
first thin I do is to set the F1 directory to the correct location. after that I open a file from the game (for exsample: toro_rosso.erp) and search for the texture i want to change.
when the texture is highlighted, I go to textures>Import, select the new texture and the EEA freezes and crash.
I hope you can find a solution to my program!
thanks!

**Comment by Ryder25** [comment]
Several other users are reporting the same issue as you. It seems all of them are on Windows 7.  I will eventually fix this, but it will take me a while since I do not have access to a Windows 7 computer at home.

**Comment by Ryder25** [comment]
I have just uploaded version 5.0. The issue should now be fixed. Please double-check and let me know.
