### ISSUE TITLE
.dds image type not supported?

### ISSUE THREAD

**Issue by matthtfcjohnson** [Ryder25/Ego-Engine-Modding#21]
I followed all of the steps in this tutorial : https://www.youtube.com/watch?v=P907smr7i1w and whenever I go to import the helmet textures I get a message saying that the image type is not supported. Any ideas?

**Comment by Ryder25** [comment]
What settings did you use to save the dds image with the Intel plugin?

**Comment by matthtfcjohnson** [comment]
Hi

Thanks for the response but I've figured it out and my helmet looks class in game. Cheers for the archiver
________________________________
