### ISSUE TITLE
surface_materials

### ISSUE THREAD

**Issue by datcb7** [Ryder25/Ego-Engine-Modding#3]
Should I be able to convert the surface_materials.xml for F1 2013/14?

Receiving an error:
http://www.theforcemedia.com.au/IMAGES/failure.jpg

**Comment by ptasev** [comment]
Yes. It must be a bug. I don't have either of those games. Can you send me the file from both?

**Comment by Ryder25** [comment]
Yes. It must be a bug. I don't have either of those games. Can you send me the file from both?

**Comment by Ryder25** [comment]
Version 2.1 has been released that should fix the issue.

**Comment by datcb7** [comment]
You are a legend!
I'll test it tonight.
I thought it was strange for me to get the error. Other people have modified the file over the years, you think they just used Notepad?  ;D

**Comment by Ryder25** [comment]
Haha, nah, conversion used to work before. I recently introduced this bug, but hopefully it's history.

**Comment by datcb7** [comment]
hey, sorry I only just got around to testing it. Everything works fine now :) Thanks again.
