### ISSUE TITLE
ERP EDITOR ingame everything is black after importing dds files

### ISSUE THREAD

**Issue by Zokah** [Ryder25/Ego-Engine-Modding#4]
when i import the DDS files ingame everything is black only the hud is still visible

**Comment by Zokah** [comment]
i saved the files in DTX3 and not in DXT5 and that was the problem
**Facepalm**

**Comment by Ryder25** [comment]
Send me example erp and dds files so I can reproduce it on my computer.

**Comment by Zokah** [comment]
the problem was the image type i used dxt1 for the paint and it should have been dxt5 so the problem is fixed
