### ISSUE TITLE
Error exporting and importing pkg files

### ISSUE THREAD

**Issue by cacolorde** [Ryder25/Ego-Engine-Modding#5]
In the preview tab for pkg, this appears:
'' files Could not create preview!

Não foi possível carregar o tipo System.Numerics.Vector4 do assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.''

When trying to import pkg, this appears:
https://gyazo.com/8b43a83855b4b0dde7f5257ba993d393

**Comment by Ryder25** [comment]
Which version of Windows, and .Net Framework do you have?

Make sure to get version .Net Framework 4.6.2

If you already have that then send me the files, and I'll have a look.

**Comment by cacolorde** [comment]
I'm downloading .Net Framework 4.6.2 , I already had 3.5 installed, but I'm guessing that was the problem. 
When it finishes i'll let you know if it works, but really thanks for the help!

**Comment by cacolorde** [comment]
Hey Ryder25, HUGE thank you for the help!! 
After installing .NET Framework 4.6.2 the problem was solved!
Thank you!!
