### ISSUE TITLE
Extracting Issue!

### ISSUE THREAD

**Issue by Bergmann121** [Ryder25/Ego-Engine-Modding#6]
I want to extract something but everytime I do that it doesn't save it. There is a message which says:
"Could not export texture! 
Mipmap file not found!"
What can I do to fix it?

**Comment by Ryder25** [comment]
Which file are you trying to extract? Are you selecting the right mipmap file before saving? You'll have to give me more info, maybe even pictures of what you've tried, before I can help.

**Comment by Bergmann121** [comment]
I want to extract a dds file from a game out on my Desktop but if I want to save it it just doesnt work. Then there is nothing inside my folder.

**Comment by Bergmann121** [comment]
https://gyazo.com/c3a752cd519cf55f366aa797cc0fb1b9

**Comment by Ryder25** [comment]
When you press export, the app will ask for the filename for saving. After, it will ask for a mipmaps file.  You need to choose the correct file in order for the export to work.

Make sure to set the F1 game folder in the Settings menu.  This will help you find mipmaps file.

**Comment by Bergmann121** [comment]
Thanks it worked.
