### ISSUE TITLE
Can't open .erp files - F1 2017

### ISSUE THREAD

**Issue by therealjeagles** [Ryder25/Ego-Engine-Modding#7]
Hi, downloaded and extracted the 5.1 ERP archiver for helmet modding on F1 2017.

I've set the directory as F1 2017 in the C drive [PF(x86)/Steam/steamapps/common], but I can't open any files in the archiver. I get a message saying: "The program could not open this file! One or more errors occurred. 

It's really frustrating as I have zero idea as to what is causing this.

**Comment by Ryder25** [comment]
The ERP Archiver does not officially support F1 2017, so that may be the cause of the problem.

Your F1 2017 directory would be PF(x86)/Steam/steamapps/common/F1 2017 based on your example

What file are you trying to open?
