### ISSUE TITLE
EGO CTF EDITOR

### ISSUE THREAD

**Issue by Alain6710** [Ryder25/Ego-Engine-Modding#8]
Bonjour, j'ai besoin d'aide,
je n'arrive pas a ouvrir Ego Ctf Editor, pour les fichiers DIRT RALLY,
Pouvez vous m'aider ?
Merci d'avance
Ci joint un screen 
![ego dysfonction](https://user-images.githubusercontent.com/31502640/29911753-574c88dc-8e2f-11e7-9423-9d0f0e07c5f5.png)

**Comment by Ryder25** [comment]
I didn't translate your text, so I have no idea what you are saying.

Dirt Rally is not supported by the CTF Editor.
